// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScanRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ScanRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infected      bool                   `protobuf:"varint,1,opt,name=infected,proto3" json:"infected,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetInfected() bool {
	if x != nil {
		return x.Infected
	}
	return false
}

func (x *ScanResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_scanner_proto protoreflect.FileDescriptor

const file_proto_scanner_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scanner.proto\x12\ascanner\"[\n" +
	"\vScanRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\"`\n" +
	"\fScanResponse\x12\x1a\n" +
	"\binfected\x18\x01 \x01(\bR\binfected\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2I\n" +
	"\x0eScannerService\x127\n" +
	"\bScanFile\x12\x14.scanner.ScanRequest\x1a\x15.scanner.ScanResponseB\fZ\n" +
	"stub/protob\x06proto3"

var (
	file_proto_scanner_proto_rawDescOnce sync.Once
	file_proto_scanner_proto_rawDescData []byte
)

func file_proto_scanner_proto_rawDescGZIP() []byte {
	file_proto_scanner_proto_rawDescOnce.Do(func() {
		file_proto_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scanner_proto_rawDesc), len(file_proto_scanner_proto_rawDesc)))
	})
	return file_proto_scanner_proto_rawDescData
}

var file_proto_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_scanner_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: scanner.ScanRequest
	(*ScanResponse)(nil), // 1: scanner.ScanResponse
}
var file_proto_scanner_proto_depIdxs = []int32{
	0, // 0: scanner.ScannerService.ScanFile:input_type -> scanner.ScanRequest
	1, // 1: scanner.ScannerService.ScanFile:output_type -> scanner.ScanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scanner_proto_init() }
func file_proto_scanner_proto_init() {
	if File_proto_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scanner_proto_rawDesc), len(file_proto_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scanner_proto_goTypes,
		DependencyIndexes: file_proto_scanner_proto_depIdxs,
		MessageInfos:      file_proto_scanner_proto_msgTypes,
	}.Build()
	File_proto_scanner_proto = out.File
	file_proto_scanner_proto_goTypes = nil
	file_proto_scanner_proto_depIdxs = nil
}
